[phases.setup]
nixPkgs = ['...', 'php82Extensions.intl', 'php82Extensions.zip']

[phases.install]
cmds = ['composer install --optimize-autoloader --no-dev --no-scripts --no-interaction']

[phases.build]
cmds = [
    'npm ci',
    'npm run build',
    'mkdir -p storage/framework/{sessions,views,cache} storage/logs',
    'chmod -R 777 storage bootstrap/cache',
    'composer install --optimize-autoloader --no-dev --no-scripts --no-interaction', 
    'php artisan config:cache',
    'php artisan route:cache',
    'php artisan view:cache',
    'php artisan event:cache'
]
[start]
cmd = 'php -S 0.0.0.0:$PORT -t public'